name: Release VSCode Extension
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build extension
        run: yarn run package
      - uses: actions/upload-artifact@v2
        with:
          name: oso_vscode_extension
          path: oso.vsix
