name: Test VSCode Extension
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: Fmt / Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Use Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: '22'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Check formatting of JS library
        run: npm run fmtcheck
      - name: Typecheck
        run: npm run typecheck
      - name: Lint JS library
        run: npm run lint
